CREATE TABLE User (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	user_name varchar(255) not null,
	password varchar(255) not null,
	role varchar(255) not null,
);

insert into User VALUES (null,'user','pw','USER');

	
